# Generated by Django 4.2.4 on 2023-09-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='Announcement',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='Assignment',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='Enrollment',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='Submission',
        ),
    ]
