# Generated by Django 4.2.4 on 2023-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_announcement_table_alter_assignment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_content',
            field=models.JSONField(default=dict),
        ),
    ]
