# Generated by Django 4.2.4 on 2023-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstructorName', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(choices=[('Science', 'Science'), ('Engineering', 'Engineering'), ('Arts', 'Arts')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
    ]
